import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Jimmy Munoz | Resume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-resume-tan-100 font-resume-ubuntu antialiased flex flex-coL">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
